### ISSUE TITLE
docs: add security model document

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1054]
This document will go over the security model for Celestia. The [LazyLedger whitepaper](https://arxiv.org/abs/1905.09274) lays out the security model for DA and we use [CometBFT](https://cometbft.com) consensus. Use these materials to draft a document on the security properties of Celestia.

**Comment by gulshanpr** [comment]
can I work on this?. btw I think the CometBFT link is broken

**Comment by jcstein** [comment]
Absolutely

**Comment by gulshanpr** [comment]
can you share an example of how the document should be drafted?

**Comment by jcstein** [comment]
hi @gulshanpr - have assigned this to Yaz as he is working on one! i'll take a look to see what other issues would be good for you

**Comment by Bidon15** [comment]
if someone wants to write a post about security for celestia DA network + consensus one, please go ahead and make a PR for the docs or learn modular part

**Comment by jcstein** [comment]
closing as not planned because it is stale
