### ISSUE TITLE
Add docs for submitting proposals to changes params

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/docs#1055]
we should add some docs with information on how to submit proposals to such things

fortunatley, there is a lot of information already surrounding this topic in https://docs.cosmos.network/v0.46/modules/gov/01_concepts.html#vote, examples such as https://github.com/celestiaorg/celestia-app/blob/32d247971386c1944d44bec1faeb000b1ff1dd51/app/test/std_sdk_test.go#L260-L276, and our specs https://github.com/celestiaorg/cosmos-sdk/blob/release/v0.46.x-celestia/x/gov/spec/03_messages.md#proposal-submission

cc @adlerjohn and @jacobarluck please add more context if needed :slightly_smiling_face:

**Comment by adlerjohn** [comment]
The documentation in this repo should include end-user instructions, i.e. that involve no code, only interaction via CLI or GUI.
