### ISSUE TITLE
fix: prevent docusaurus from opening chrome on `yarn start`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1064]

**Comment by gulshanpr** [comment]
if the fix is for not opening *any browser* by default, when doing `yarn start` (instead have to go to http://localhost:3000/ manually) i can make a PR.
but im not sure about, preventing docusaurus to open only the chrome browser.

**Comment by jcstein** [comment]
preventing browser opening will do!

**Comment by gulshanpr** [comment]
Can you review this.

**Comment by jcstein** [comment]
of course, merged! :shipit:

**Comment by gulshanpr** [comment]
Thanks for merging @jcstein.
I have few questions: 
1. How can I pass this 'depoly preview' fails check,
2. Is it a good practice to make a PR to a issue, that I discussed but didn't got assigned?
