### ISSUE TITLE
Change "click here" to more actionable items for URLs

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#1073]
Based on context found here:

https://www.w3.org/QA/Tips/noClickHere
https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/

**Comment by jcstein** [comment]
For example, instead of saying "Learn how to stake on your own at the community dashboards
listed [here]", we could say "Learn how to [stake on your own at the community dashboards]" and just link that part of the sentence.
