### ISSUE TITLE
Dead link for keyring-backend external docs.

### ISSUE THREAD

**Issue by MicahZoltu** [celestiaorg/docs#1097]
https://github.com/celestiaorg/docs/blob/3da9aa83d3dc887d4c26ec1866f36b4c4886c750/docs/nodes/celestia-app-commands.md?plain=1#L51

Dead link (404).

**Comment by jcstein** [comment]
thank you @MicahZoltu - it looks like the link has changed to: https://docs.cosmos.network/main/user/run-node/keyring
