### ISSUE TITLE
Explain Slashing in the Docs

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#11]
Feedback from one of the validators is to explain the slashing mechanics in consensus using the docs.

**Comment by Mackenzie-OO7** [comment]
Hi @jcstein Can I work on this?

**Comment by jcstein** [comment]
cc @YazzyYaz as I believe he may be working on this currently

**Comment by Mackenzie-OO7** [comment]
@YazzyYaz I'd like to pick this up, could I?

**Comment by jcstein** [comment]
yes, please go for it @Mackenzie-OO7

**Comment by Mackenzie-OO7** [comment]
Hi @jcstein please where exactly in the docs should I put this?

**Comment by jcstein** [comment]
i'll review that when i take a look at your PR!
