### ISSUE TITLE
chore: update full-stack guide with OP stack

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1120]
The Ethermint that was used to make the full-stack modular blockchain development guide is now out of date. This issue is to modify the tutorial to use a local OP stack devnet instead of Ethermint.

Once finished, add these links back to the rollups overview page and developers/overview page

```md
- Full-stack modular blockchain development
  - [Build a full stack modular dapp with React, Vite, RainbowKit, Celestia and Foundry](./full-stack-modular-development-guide.md)

- Full stack modular [blockchain development guide](../../developers/full-stack-modular-development-guide/)
```

**Comment by 0xFloyd** [comment]
would love this

**Comment by Etimfon007** [comment]
Hello @jcstein has this been assigned to anyone already?
I'll love to take it up.

**Comment by jatin9996** [comment]
I would love to take this issue

**Comment by Etimfon007** [comment]
That's okay
