### ISSUE TITLE
Core/App Doc Updates

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#1122]
- [x] Update https://docs.celestia.org/nodes/instantiate-testnet/ so that old commands like `evm-address` are removed and it follows latest celestia-app a7d85622372ab03ef1a32c221303b6c89e8f3add
- [x] Add step on adding seeds and peers to networks repo after on that same page somewhere after starting their validator aea212727087a207a256f5616f513576a5e1701c
- [x] Add context on not using persistent_peers unless using a sentry node https://github.com/celestiaorg/docs/pull/1129/commits/5ef48eeb01c9760fa8e995f9b3526285ddb69be0
- [ ] Decide if indexing needs to use `kv` or null
- [ ] Decide if we want to set discard_abci_responses to true in the default and document it

**Comment by jcstein** [comment]
note: check into registering evm address for QGB, this step may be needed in addition to the current setup

more setup also may be needed to set up a qgb testnet, too
