### ISSUE TITLE
Document "Which IBC version does your network use?"

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#1140]
## Context

We received this question: "Which IBC version does your network use?"

## Proposal

Add to docs that celestia-app currently uses [v6.2.0](https://github.com/celestiaorg/celestia-app/blob/2335d2b7d8d9463abc85f79b430926380dd41001/go.mod#L35). Potential location for this Q/A https://docs.celestia.org/nodes/ibc-relayer/

Note: the ibc-go version used by celestia-app could change in the future. I don't expect the docs to be kept immediately in sync with the version used in go.mod so if we don't want to explicitly state `v6.2.0`, we could say something like check the latest celestia-app release go.mod for the version of ibc-go that is currently used.

**Comment by jcstein** [comment]
thanks for putting this issue in. I'll plan to add this with our update to the IBC guide
