### ISSUE TITLE
Add CI job to check output

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/docs#116]
This isn't easily maintainable. A CI job should be added that runs the above steps, then runs `celestia version` and compares the output to these lines.

_Originally posted by @adlerjohn in https://github.com/celestiaorg/docs/pull/109#discussion_r882871257_

**Comment by jcstein** [comment]
I'm cleaning up issues and closing this as it is stale. The "Latest Tags" automation has helped out a lot for updating versions.
