### ISSUE TITLE
Docker Light Node fails to start second time and Docker Docs Are Incorrect for Start

### ISSUE THREAD

**Issue by keyneom** [celestiaorg/docs#1228]
The example command for starting the node is the same as what is used to init as seen here:

https://docs.celestia.org/nodes/docker-images#start-the-node

Additionally, you can just start the node to begin with and it will run the init anyways, perhaps the current process is just to simplify keeping track of the address and mnemonic.

The first time the docker container is started and running it appears to function properly, but once stopped if you try to restart the container or create a new container referencing the same volume the client complains about permissions on the file.

```
2023-10-31 13:03:32 Error: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".ConstructModule.Listen.func2 (/src/nodebuilder/p2p/addrs.go:14): failed to build host.Host: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".routedHost (/src/nodebuilder/p2p/host.go:38): failed to build p2p.HostBase: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".host (/src/nodebuilder/p2p/host.go:43): failed to build peer.ID: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".id (/src/nodebuilder/p2p/identity.go:45): failed to build crypto.PrivKey: received non-nil error from function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".Key (/src/nodebuilder/p2p/identity.go:17): keystore: permissions of key 'p2p-key' are too relaxed: required: 0600, got: 0777
```

**Comment by jcstein** [comment]
the command in reference is in the ["light node setup with persistent storage" section](https://docs.celestia.org/nodes/docker-images#light-node-setup-with-persistent-storage), so the section prior to this is how to just start the node to begin with. i'm a little unclear about what the actual issue is here?

**Comment by jcstein** [comment]
i'm hitting a separate error when following the PR above's version of the guide, [here are the logs](https://app.warp.dev/block/uHLpWIQmexbgmDn8sk2BxT)

**Comment by jcstein** [comment]
fixed in the PR. you can [see the preview of the page](https://docs.celestia.org/pr-preview/pr-1237/nodes/docker-images) until the PR is merged

**Comment by keyneom** [comment]
That looks like it corrects the docs issue for starting the node (sorry if my initial message was unclear, but yes I was trying to convey that the command for start was actually just running the init command again). 

Regarding the errors you are seeing when running the new PR's version of the docs. The command I'm seeing that was run in this warp (https://app.warp.dev/block/uHLpWIQmexbgmDn8sk2BxT) is not the command that the new docs use. Although, it is possible that the error you are encountering is a result of not having run the chown command from the docs:
```
sudo chown 10001:10001 $HOME/my-node-store
```

because it appears you do not have write permissions. Your command is still using `/home/celestia/` as the volume when the new docs switched it to just `/celestia`. I haven't tried running the new docs yet so I can't say for sure if things work now but I'll try a little later today when I get a chance.

**Comment by keyneom** [comment]
Just tested using the new documentation given the preview link you sent. It looks to be working correctly now.

**Comment by keyneom** [comment]
Whoops, I take that back. It looks like it isn't making use of the `my-node-store` so persistence is not working. It's generating a new mnemonic on each start.

**Comment by keyneom** [comment]
Looking at the docker environment variables, it appears to have `CELESTIA_HOME` set to `/home/celestia` when I assume based off of the changes you made to the documentation that you want that switched to `/celestia` to write to the mounted volume.

**Comment by keyneom** [comment]
After overriding the CELESTIA_HOME environment variable by setting it to `/celestia` to match the mounted volume, I receive the same error regarding permissions.

![image](https://github.com/celestiaorg/docs/assets/1523791/31d4e7e8-f59c-4f22-9ca4-dcb1b14b3657)

When attempting to run the node a second time (Running init first, then the start command, then stopping the container, then starting the container again or starting a new container) it fails to continue running with the error above.

**Comment by keyneom** [comment]
And in thinking about it I think I know what the issue is. I'm trying to run the commands from WSL2 but I'm mounting to my windows drive. That drive should be using NTFS which won't allow for setting permissions via chmod (i.e. running in docker is likely not going to work in windows without adjusting how permissions are handled). I'll try mounting the volume to my WSL home directory (that's what you get for not following directions I guess).

**Comment by keyneom** [comment]
Init and multiple starts works when mounting to my WSL2 home directory.

To be clear:
- The preview documentation fixes the issue where the init command was used instead of the start command
- The preview documentation switches to using `/celestia` instead of `/home/celestia` which ends up preventing the persistence of the nodes keys, etc
- Overly relaxed permissions are an issue if trying to run the docker containers in Windows but running within a non-NTFS mount inside of WSL2 works fine.

In order to avoid the issue with the CELESTIA_HOME environment variable leading to non-persistent runs, I overrode the value in both the init and start commands by adding the following:
```
-e CELESTIA_HOME=/celestia
```

immediately following this portion of the commands:
```
docker run -e NODE_TYPE=$NODE_TYPE -e P2P_NETWORK=$NETWORK 
```
