### ISSUE TITLE
Celestia Node setup

### ISSUE THREAD

**Issue by Swornatoya** [celestiaorg/docs#1252]
I am trying to setup a node for Celestia where I can get all the details related to a block and address and also all of its transactions. So will it help if I setup the full storage node?
When I try to click on the link present in the page https://docs.celestia.org/nodes/full-storage-node to Install Celestia-node it says page not found. Please help me on this

![image](https://github.com/celestiaorg/docs/assets/101313232/fef3137f-cdc7-4207-ac44-32dc05dec85e)

![image](https://github.com/celestiaorg/docs/assets/101313232/c34ed623-9a16-4a1f-ab10-cccc4f503ae5)

**Comment by jcstein** [comment]
<img width="976" alt="scrot 2023-11-06 at 1 05 22 PM" src="https://github.com/celestiaorg/docs/assets/46639943/c22acbb6-db94-4bb1-bc1b-c43a28789992">

i can confirm the page is up. please try to hard refresh your browser!

for using the celestia-node CLI, check out the [node tutorial](https://docs.celestia.org/developers/node-tutorial)

for interacting with the node api, [refer to node rpc docs](https://node-rpc-docs.celestia.org/?version=v0.12.0)

i am going to close the issue, but please feel free to open it up if you need

**Comment by jcstein** [comment]
found the link you were having issues with, made pr to fix!

**Comment by Swornatoya** [comment]
I am still getting the same 404 error when I try clicking on the link "the tutorial to install the celestial node". 
Even from github "https://github.com/celestiaorg/celestia-node#api-docs" when I try clicking in the link "here" for the API documents as shown in the below image that also navigates to 404 not found.

Is this the offical API and does it have a long term support?

![image](https://github.com/celestiaorg/docs/assets/101313232/429c6725-4680-4b72-be19-247621c7a267)

![image](https://github.com/celestiaorg/docs/assets/101313232/fa2065a1-eee4-44e5-b8e7-542de8af3eaa)

**Comment by jcstein** [comment]
and the issue on `celestia-node` is separate and on that repo, so i'll make a PR to fix that

**Comment by jcstein** [comment]
https://github.com/celestiaorg/celestia-node/pull/2916
