### ISSUE TITLE
Archival Node and Rest API for Celestia

### ISSUE THREAD

**Issue by Swornatoya** [celestiaorg/docs#1256]
Is there any official Rest API for Celestia with long term support. If present any documentation for it.

I am planning to setup a mainnet  Archival non pruned node for Celestia shall I use "export NETWORK=celestia" and "export NODE_TYPE=full". What shall I use for the RPC endpoint. I am trying to setup through docker, so I am following the steps given in https://docs.celestia.org/nodes/docker-images . But I don't see any volume mapping here.

**Comment by jcstein** [comment]
no, there is no REST API. please see [the yellow callout in this section](https://docs.celestia.org/developers/node-api#gateway-api)

as i mentioned in the other issue, [this pr](https://github.com/celestiaorg/celestia-node/pull/2916) fixes the broken link you followed and replaces it with one to https://node-rpc-docs.celestia.org, for the JSON RPC docs

for RPC endpoints, here is a dashboard by a community member that is useful: https://celestia-tools.brightlystake.com/
which can be found in the [mainnet beta page in this section](https://docs.celestia.org/nodes/mainnet#grpc-endpoints)

**Comment by jcstein** [comment]
[for docker there is a section on running persistent storage already ](https://docs.celestia.org/nodes/docker-images#light-node-setup-with-persistent-storage)

**Comment by Swornatoya** [comment]
I tried setting up through docker command using the below steps:
1. export NETWORK=celestia
2. export NODE_TYPE=full
3. export RPC_URL=http://localhost:26657
4. docker run -e NODE_TYPE=$NODE_TYPE -e P2P_NETWORK=$NETWORK  -v /NewDisk45Machine/node-celestia/data:/home/celestia ghcr.io/celestiaorg/celestia-node:v0.12.0 celestia $NODE_TYPE start --core.ip $RPC_URL --p2p.network $NETWORK

But getting the below error:
![image](https://github.com/celestiaorg/docs/assets/101313232/ebeca488-0152-44b6-b216-bd4b36f4c5d0)

**Comment by jcstein** [comment]
hey, working on this in #1237 !
