### ISSUE TITLE
Issue while setting up the full node

### ISSUE THREAD

**Issue by Swornatoya** [celestiaorg/docs#1260]
I followed the below steps while setting up the node.
1.  export NETWORK=celestia
2.  export NODE_TYPE=full
3.  export RPC_URL=http://localhost:26657
4.  sudo docker run -e NODE_TYPE=$NODE_TYPE -e P2P_NETWORK=$NETWORK  -v /**/node-celestia/data:/home/celestia ghcr.io/celestiaorg/celestia-node:v0.12.0 celestia $NODE_TYPE start --core.ip $RPC_URL --p2p.network $NETWORK

All required ports are opened (2121, 26658, 26659, 9090, 26657)

But I am getting the below error as shown in the screenshot. Please help me setup the node:

![image](https://github.com/celestiaorg/docs/assets/101313232/5c509418-3577-493e-8215-84decea89faf)

**Comment by jcstein** [comment]
please ask questions like this in discord, unless there is an issue!

https://docs.celestia.org/nodes/mainnet#da-rpc-endpoints
