### ISSUE TITLE
Add docs for rollup data roots

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/docs#1262]
We should have dedicated documentation for how rollups should use a blob share commitment for their data root.

**Comment by jcstein** [comment]
docs notes for me to work on to improve blobstream docs:
1. write out how to create pfb, take committment, height, and use that in your data root
2. write about data formatting and encoding, how you commit to the data, take commitment and put in header
3. https://github.com/celestiaorg/docs/pull/1261
4. general doc on rollup committing to data
