### ISSUE TITLE
Update release branch for proper blobstream CLI recognition

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/docs#1269]
When following the instructions provided in the [blobstream binary installation guide](https://docs.celestia.org/nodes/blobstream-binary#install), i.e.,

   ```
   git clone https://github.com/celestiaorg/orchestrator-relayer.git
   cd orchestrator-relayer
   git checkout v0.3.0-app-v0.13.2-beta
   make install
   ```

An issue happened where the `blobstream` CLI command is not recognized. 
Upon further investigation of the checked-out branch, specifically examining the [Makefile in version `v0.3.0-app-v0.13.2-beta`](https://github.com/celestiaorg/orchestrator-relayer/blob/bb743f530a759ddd69387185b36a90d0961b6218/Makefile#L9), it becomes apparent that in this version, the renaming of `qgb` to `blobstream` has not yet taken place.

To resolve this issue, a different release branch should be considered that has the `qgb` to `blobstream` renaming already implemented.

**Comment by jcstein** [comment]
it looks like this tutorial is just locked on an older version [than latest ones](https://github.com/celestiaorg/orchestrator-relayer/releases). @SweeXordious should I bump this to [v1.0.0-rc7](https://github.com/celestiaorg/orchestrator-relayer/releases/tag/v1.0.0-rc7)?

**Comment by SweeXordious** [comment]
Thanks a lot
