### ISSUE TITLE
making figures consistent in the blobstream intro

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/docs#1271]
In the [intro to blobstream](https://docs.celestia.org/nodes/blobstream-intro#blobstream), two figures are supplied one as the continuation of the other i.e., 

https://docs.celestia.org/img/blobstream/blobstream-orchestrator.png 

and 

https://docs.celestia.org/img/blobstream/blobstream-relayer.png 

The first image illustrates that _attestations_ are coming from the _celestia validator node_, while in the second figure the source of attestations changes to the _celestia app consensus node_.  If this discrepancy is not intentional, then it is worth updating the figures to make them consistent.

**Comment by staheri14** [comment]
A minor side note: there is also a discrepancy in coloring between the _validator node_ and the _Celestia app consensus node_. They could become consistent in terms of color as well.

**Comment by jcstein** [comment]
thank you for this issue! i plan to remove these older diagrams in favor of the [newer version in the top of the overview section](https://docs.celestia.org/img/blobstream/Blobstream.png) and also reworking the intro pages (https://docs.celestia.org/developers/blobstream & https://docs.celestia.org/nodes/blobstream-intro) [based on this from github](https://github.com/celestiaorg/blobstream-contracts#send-a-message-from-celestia-to-an-evm-chain)
