### ISSUE TITLE
Blobstream docs feedback

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#1275]
I have some feedback from reading the first four page of Blobstream docs

1. ✅ The links to these two ADRs seems out of place. The topics of: valsets and data commitments haven't been introduced yet so this assumes some prior knowledge. https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-intro.md?plain=1#L36-L41
2. ✅ The term `ValSet` is written with inconsistent casing. Sometimes it is `Valset`. Sometimes it is `ValSet`. We should use consistent casing. IMO the best form to use is `ValidatorSet`
3. ✅ In this diagram, why is there an arrow from Celestia validator node to Blobstream relayer? That line isn't explained in the text. https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-intro.md?plain=1#L52 
4. ✅ The Golang version for Blobstream claims 1.20.2 but the repo uses 1.21 so I think this constant needs to be bumped https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-binary.md?plain=1#L18 
5. ✅ https://docs.celestia.org/nodes/blobstream-binary contains content copy + pasted from the README of blobstream. I don't think it should contain the Contributing section b/c that's applicable to readers of the Github README but not as applicable to readers of the docs (who just want to run the binary).
6. ✅ The blockspace race is over and I don't think the network is still supported. Proposal to remove: https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L25-L27
7. ✅  What does "This latter" mean? https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L45
8. ✅ "The team" is a bit vague here. Proposal to delete that sentence entirely. https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L46
9. ✅ There are no flags listed in https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L112-L121
10. ✅ What does "find the latter" mean here? https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L123C31-L123C31
11. ✅ I think this section should come before the start command: https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L139
12. ✅ "This latter" doesn't make sense https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L163
13. ✅ Remove this note about BSR https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L280
14. ✅ Multiple other instances of "This latter" which don't make sense.

cc: @SweeXordious

**Comment by jcstein** [comment]
thank you for this feedback, super helpful! notes from slack:

i’m working on consolidating these two pages and finding a home for the intro page, what do you think of that? at least, i’d like to make nodes/blobstream-intro more accurate [based on this ](https://github.com/celestiaorg/blobstream-contracts#send-a-message-from-celestia-to-an-evm-chain) from github
https://docs.celestia.org/developers/blobstream
https://docs.celestia.org/nodes/blobstream-intro

and keeping nodes/blobstream-* to be only things that are relevant to running the orchestrator-relayer. on that note, [the docs that are imported from orchestrator-relayer repo]

https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/importBlobstream.mjs#L5-L20 and need to be edited in the source there before being added to docs site are:
https://docs.celestia.org/nodes/blobstream-orchestrator
https://docs.celestia.org/nodes/blobstream-keys
https://docs.celestia.org/nodes/blobstream-relayer
https://docs.celestia.org/nodes/blobstream-deploy
- one that is missing from this import is the [bootstrapper.md doc](https://github.com/celestiaorg/orchestrator-relayer/blob/main/docs/bootstrapper.md) and i think it may be something that should be in the node section

**Comment by rootulp** [comment]
> i’m working on consolidating these two pages and finding a home for the intro page, what do you think of that?

Makes sense to me.

> the docs that are imported from orchestrator-relayer repo

ahh so does that mean the issues I suggested above should not be fixed in the docs repo but should be fixed in the orchestrator-relayer repo?

**Comment by jcstein** [comment]
I'm going to pushed to a branch shortly with a reformatted blobstream-intro and updated blobstream-binary, addressing your points 1-5

> ahh so does that mean the issues I suggested above should not be fixed in the docs repo but should be fixed in the orchestrator-relayer repo?

the others are still relevant to docs, but just need to be edited in orchestrator-relayer first, then pulled in (i'll get to this automation eventually, for now the script works)

> > i’m working on consolidating these two pages and finding a home for the intro page, what do you think of that?

> Makes sense to me.

I think i'm going to keep the page, but change the title and content in the node category, so it is clear it's for validators

<img width="651" alt="scrot 2023-11-17 at 2 46 11 PM" src="https://github.com/celestiaorg/docs/assets/46639943/0485d3ae-202a-41a9-bdb7-3b584f045f87">

**Comment by jcstein** [comment]
I will make changes for 6-14 next week (if SweeXordious doesn't beat me to it), 1-5 addressed in #1261

**Comment by SweeXordious** [comment]
👍 👍 @jcstein Let me know if you need any information about these changes or want me to handle any of them

**Comment by jcstein** [comment]
I'll go ahead and update orch-relayer repo today and make a PR @SweeXordious

**Comment by SweeXordious** [comment]
Awesome, thanks a lot

**Comment by jcstein** [comment]
you're welcome! for "10. What does "find the latter" mean here? https://github.com/celestiaorg/docs/blob/756234bb6be524c2cc8f7ba674f645d7cd8b0a1e/nodes/blobstream-orchestrator.md?plain=1#L123C31-L123C31" @SweeXordious what is "latter" referring to here?

**Comment by SweeXordious** [comment]
@jcstein `the orchestrator's TOML config file`

**Comment by jcstein** [comment]
https://github.com/celestiaorg/orchestrator-relayer/pull/603 🫡
