### ISSUE TITLE
Balance calculation of a celestia address

### ISSUE THREAD

**Issue by Swornatoya** [celestiaorg/docs#1287]
When I tried calculating the balance of a celestia addrress : celestia1wd3j8e02t6k9d6knxg85kps05qra3fy4nd39rs
In explorer it shows the balance as 60.09 TIA. But as per the transactions data shown in the explorer the amounts when summed up does not match up the balance. As per the below transactions there are two amounts that are transferred 225.00 TIA and 9.77 TIA. So if we consider this the balance becomes negative. 
Please help me know where I am going wrong here.
![image](https://github.com/celestiaorg/docs/assets/101313232/a33395ab-e7c5-45c0-8e5b-57ad0724c17f)

**Comment by jcstein** [comment]
~294.98 (your genesis amount) - 225.00 - ~0.025 (fee for send) - 60 (delegated) - ~0.04 (fee for delegation) + 60 (undelegation) - ~0.05 (fee for undelegation) - 9.77 - ~0.025 (fee for send) = ~60

**Comment by Swornatoya** [comment]
Thank you this was really helpful
