### ISSUE TITLE
Document remote signing a blob and submitting via StateModule `SubmitTx` 

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/docs#1291]
We have some users that want to remote-sign blobs and submit them and are looking at the `BlobModule` for doing so (which is incorrect).

If users wan't to "remote sign" a PFB, they'd have to build the blob on their own, sign over it and submit it via the `SubmitTx` endpoint on the StateModule. 

We need to have some docs around this (ideally some code snippets) on how it can be done. 

Happy to provide the snippet.

**Comment by Wondertan** [comment]
cc @jcstein

**Comment by jcstein** [comment]
happy to add this to docs! could you please provide the snippets here?

**Comment by jcstein** [comment]
bump for 2024

**Comment by jcstein** [comment]
bumping again cc @renaynay and @Wondertan for the snippet!

**Comment by renaynay** [comment]
Ah i had the snippet a while ago, will have to dig it up again.

**Comment by jcstein** [comment]
no worries @renaynay, that works. thank you

**Comment by jcstein** [comment]
closing as not planned for now as this is stale. please reopen if you think this is urgent and necessary!
