### ISSUE TITLE
feature request: create workflow so that when orchestrator-relayer/docs has an update, it pushes update here

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1299]
using a similar workflow to [the existing `yarn import-blobstream` script](https://github.com/celestiaorg/docs/blob/main/importBlobstream.mjs)

**Comment by ogunleye0720** [comment]
hello @jcstein , I can recreate the JavaScript code similar to the import-blobstream.mjs But how does the code get executed ? are we using github actions to execute the script ?

**Comment by jcstein** [comment]
yes this would be github actions so a github workflow
