### ISSUE TITLE
Update docs for node

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/docs#1308]
* New release https://github.com/celestiaorg/celestia-node/releases/tag/v0.12.1
* New build option `make build-jemalloc` (details on the release)
* Decreased resource requirements
	* BN/FN -> to 4GiB min RAM
	* LN -> 500MiB min RAM

**Comment by jcstein** [comment]
thanks for this issue @Wondertan.

for what type of user full/light/bridge would you recommend using the `make build-jemalloc` flag command as opposed to `make build`?

**Comment by Wondertan** [comment]
All of them. We should add somewhere: "NOTE: This build option enables CGO"

**Comment by jcstein** [comment]
thanks! i'll change the existing instances to this and add the note
