### ISSUE TITLE
bug: mocha rpcs not working

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1337]
reported from community:

the below rpc endpoints of Mocha are not available now on https://docs.celestia.org/nodes/mocha-testnet.
- [full.consensus.mocha-4.celestia-mocha.com](http://full.consensus.mocha-4.celestia-mocha.com/)
- [consensus-full-mocha-4.celestia-mocha.com](http://consensus-full-mocha-4.celestia-mocha.com/)

cc @celestiaorg/devops

**Comment by smuu** [comment]
Those two are listed under `Bridge, full, and light nodes` which are not intended for the use of a plain RPC endpoint. It is used to point a DA node, like a bridge to a consensus node with rpc port 26657 and grpc 9090.
The main RPC endpoint to use for mocha is: https://rpc.celestia-mocha.com/.

This is another reason to put the consensus endpoints over the DA endpoints.

Another option would be to explain in the docs that the DA endpoints are not exposing HTTP or https ports.

**Comment by jcstein** [comment]
thanks @smuu - going to pick this up after holiday. i think we should work together to reformat the existing arabica/mocha pages to be more like the mainnet page

**Comment by jcstein** [comment]
I think i'll re-work this page similarly to https://docs.celestia.org/nodes/arabica-devnet
