### ISSUE TITLE
docs: Document the node's store structure clearly

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/docs#1341]
Not sure if this is already done, but I looked through docs and was unable to find.

We should document the node's datastore and its contents.

**Comment by jcstein** [comment]
can you please provide more context? where should i reference to document this?

**Comment by jcstein** [comment]
@renaynay gm!

**Comment by jcstein** [comment]
bumping this again @renaynay and @Wondertan

**Comment by renaynay** [comment]
Hey sorry, what I meant by this was documenting which directories relate to which structures

e.g. `/blocks` stores blocks, `/data` is headers etc.

**Comment by jcstein** [comment]
got it. I will begin drafting here

`/blocks` - stores blocks
`/data` stores headers
`/config` stores:
- `app.toml` - what are these 3 for?
- `client.toml`
- `config.toml`
`/config.toml` is node config
`/inverted_index` - what is the correct definition for this @renaynay?
`/keys` - stores keys
`/transients` - what is the correct definition for this?

**Comment by Mackenzie-OO7** [comment]
Hi! @jcstein can I work on this?

**Comment by Mackenzie-OO7** [comment]
@jcstein please where do you suggest I should put this in the docs?

**Comment by jcstein** [comment]
do you think "run a node" -> "resources" -> "celestia-node" is a good spot?

**Comment by Mackenzie-OO7** [comment]
> do you think "run a node" -> "resources" -> "celestia-node" is a good spot?

Yes! that's what I had in mind
