### ISSUE TITLE
Clarify if blobstream orchestrator is required or recommended for validators

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#1370]
## Context

A validator is asking if running the blobstream orchestrator is required.

## Problem

AFAICT the docs don't clearly state if the blobstream orchestrator is required, recommended, or optional for validators.

## Proposal

Clarify in https://docs.celestia.org/nodes/blobstream-binary or https://docs.celestia.org/nodes/blobstream-orchestrator

cc: @rach-id

**Comment by rootulp** [comment]
https://docs.celestia.org/nodes/consensus-node#run-a-blobstream-orchestrator says **incredibly important** so I infer it's recommended but not required.

**Comment by rach-id** [comment]
It is the same as running a celestia-node bridge node. But, since we will proceed with deploying BlobstreamX instead, we will probably just get rid of that documentation and the need for validators to run orchestrators altogether.

**Comment by rootulp** [comment]
Thanks for confirming. I can update the docs to clarify that blobstream orchestrator is optional.

**Comment by rach-id** [comment]
it's not, it's super important to run. and if less than 2/3rds are running orchestrator, currently for mocha, our deployment on Sepolia and Arbitrum Sepolia will halt.

I guess it's better to leave it as we will remove it in the right time once we introduce BlobstreamX.

**Comment by rootulp** [comment]
I think you're saying it's required for mocha and optional for mainnet (?)

I think the phrase "super important" conveys that it is recommended to run but not required. The point of this issue is to clarify the expectations for validators.

**Comment by rootulp** [comment]
@rach-id would you like to update the docs for this given https://github.com/celestiaorg/docs/pull/1371 may not be what you had in mind?

**Comment by rootulp** [comment]
Based on a Slack thread, closing this as won't do. Instead we're considering remove the orchestrator-relayer docs from this repo that are no longer relevant.
