### ISSUE TITLE
feat: consider splitting consensus nodes into 2 pages again

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1428]
would revert https://github.com/celestiaorg/docs/pull/1107

**Comment by jcstein** [comment]
based on your feedback, it sounds like this should still be 1 page? or is it better as 2?

**Comment by mindstyle85** [comment]
> based on your feedback, it sounds like this should still be 1 page? or is it better as 2?

no, separate page, eg same like we have for Data Availability - light node or bridge node or full storage node

here maybe we can have:

- Consensus 
   - consensus full node
   - validator

**Comment by Mackenzie-OO7** [comment]
Hii 👋🏾 @jcstein can I work on this?

**Comment by jcstein** [comment]
yes please! to start, splitting back into two pages. and then, adding feedback from P-OPSOn Mar 8, 2024, at 12:45 PM, Levai Mackenzie Ágbàrà ***@***.***> wrote:﻿
Hii 👋🏾 @jcstein can I work on this?

**Comment by Mackenzie-OO7** [comment]
@jcstein in this PR, should I also update the links in the docs that point to the old page, or should I make a new PR particularly for that?

**Comment by jcstein** [comment]
yep! let's do it all in this one. i'll work with you too and be reviewing it
