### ISSUE TITLE
Add Madara docs under "Deploy a Rollup -> Ethereum L2s -> Starknet"

### ISSUE THREAD

**Issue by SamrendraS** [celestiaorg/docs#1456]
Madara supports building app chains and integrating them with Celestia.
Documentation to do the same is missing on Celestia docs.

**Comment by SamrendraS** [comment]
Can this be assigned to me?

**Comment by SamrendraS** [comment]
Have made required changes in https://github.com/celestiaorg/docs/pull/1457

**Comment by jcstein** [comment]
closing as this is stale, but please feel free to reopen to add this!
