### ISSUE TITLE
feat: add docs for syncing from trusted hash and height

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1460]
1. go to `~/.celestia-light-mocha-4/config.toml` and change `DASer.SampleFrom` to the trusted height
2. set `--headers.trusted-hash`
cc @S1nus for feedback. is the snapshot still required? or do we JTMB all previous heights < trusted height?

**Comment by S1nus** [comment]
it just trusts them if you do this

**Comment by jcstein** [comment]
awesome, makes sense!

**Comment by jcstein** [comment]
steps from @Bidon15:
1. curl the rpc endpoint for the latest block -1
2. take the hash
3. init the light node with pre-defined config.toml
4. experience immediate success

**Comment by jcstein** [comment]
1. Get trusted height & hash [on Celenium](https://celenium.io/)
2. Set the trusted height & hash
3. Open your config.toml:
```bash
code ~/.celestia-light/config.toml
```
4. Set `DASer.SampleFrom` to the trusted height.
5. Initialize the node store
```bash
celestia light init
```
6. Run the node
```bash
celestia light start --headers.trusted-hash <hash>
```

**Comment by jcstein** [comment]
draft info portion for the documentation of this feature:

syncing to a trusted hash means that you will not sample the entire chain. this adds a trust assumption that you trust the history of chain up to that point and that you trust the entity where you get the hash from. in this case, Celenium

**Comment by jcstein** [comment]
note: if you're using all of these light nodes for similar things like tracking the same rollup, I'd recommend using the same hash/height for them all. you can also skip the celenium part and do step 1 programmatically with a consensus rpc (like the core.ip you provide to a light node, whether it's from a provider or from your own consensus node)

**Comment by jcstein** [comment]
I think that the above suggestion may not be ideal for fresh nodes:

1. Get trusted height & hash
1. Initialize the node store
    1. `celestia light init`
1. Set the trusted height & hash
    1. Open your config.toml `code .celestia-light/config.toml`. Set `DASer.SampleFrom` to the trusted height.
1. Run the node with the hash and flag:
```sh
celestia light start --headers.trusted-hash <hash>
```
