### ISSUE TITLE
feat: document mainnet.sh script in celestia-app

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1467]
Notes from @rootulp on how to view logs:

View log file:
```
cat mainnet.log
```

View actively running process which is piping into a log file:
```
tail -f mainnet.log
```

To stop the process:
```
ps aux | grep celestia-app
kill <PID>

# if that doesnt' work
kill -9 <PID>
```

_Originally posted by @jcstein in https://github.com/celestiaorg/celestia-app/issues/3166#issuecomment-1983943425_

**Comment by Bidon15** [comment]
this is not ok to put into docs. 
Ideally, this should be a community support doc(i.e. medium blog post or smt similar) that is hosted by the 3rd party (any validator team or rpc team, etc.)
