### ISSUE TITLE
bug: OP Stack

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1468]
[from discord message
](https://discord.com/channels/638338779505229824/804370245778276374/1215561404363448340)

> https://docs.celestia.org/developers/optimism-devnet
> This document seems to be outdated, I built it on the celestia-develop branch. When I execute make devnet up, it will always block in the
> ```
> forge script scripts/Deploy.s.sol:Deploy --sender 0x6bcaaf0175e2eb5693ea3d937bab1b49cce6471c --rpc-url http://127.0.0.1:8545 --broadcast --unlocked
> ```
> 
> The log of make shows that l1 keeps requesting Served eth_getTransactionByHash multiple times

**Comment by tuxcanfly** [comment]
Fixed in https://github.com/celestiaorg/docs/pull/1480 by updating dev branch.
