### ISSUE TITLE
feat: fee grant module doc

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/docs#1470]
```[tasklist]
### Tasks
- [x] add and test celestia-app portion of guide
- [ ] add and test celestia-node portion of guide
```

**Comment by jcstein** [comment]
> The feegrant module is a [module of the Cosmos-SDK](https://github.com/cosmos/cosmos-sdk/blob/main/x/feegrant/README.md). It can be thought of similarly to how on Ethereum, users can interact with a contract that has a “paymaster” who will pay for the transactions or mints for other users.

**Comment by rootulp** [comment]
This [gist](https://gist.github.com/rootulp/c47606e177aad1f8959ea31fa077ca5e) may help. It was not obvious to me that if you want a feegranter to pay fees for a feegrantee, then the commands the feegrantee invokes (via CLI) should not specify a `--fees` CLI flag.

**Comment by jcstein** [comment]
process in docs could go:
1. set up a new light node with no funds
2. set up fee grant in celestia-app
3. send pfb from the light node celestia-node
