### ISSUE TITLE
docs: celestia-node's `--node.store` flag is no longer necessary on RPC requests using default node stores

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1531]
https://github.com/celestiaorg/celestia-node/pull/3246

It will still be used:
1. in the cel-key utility: https://docs.celestia.org/developers/celestia-node-key#steps-for-generating-node-keys
2. for using a different directory than the standard dir: https://docs.celestia.org/nodes/celestia-node-troubleshooting#changing-the-location-of-your-node-store

**Comment by jcstein** [comment]
the node.store flag still exists, it's just not needed for rpc requests for someone using the default node store

**Comment by mastergaurang94** [comment]
p0 😲
