### ISSUE TITLE
feature request: implement diataxis

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1534]
https://diataxis.fr/

**Comment by Mackenzie-OO7** [comment]
@jcstein is this open to work on too? also, concerning the organization, do you have anything in mind?

**Comment by jcstein** [comment]
assigning myself to work on this one! thank you 😄

**Comment by jcstein** [comment]
unless you go for it first, but it will be a biiiiiig overhaul

**Comment by Mackenzie-OO7** [comment]
> assigning myself to work on this one! thank you 😄


cool. but i’d still like to assist you, if you don’t mind👀

**Comment by jcstein** [comment]
sounds good!

here's what I'm thinking for categories:

- Learn (as it exists)
- How to (how to run a node, run op stack, etc.)
- Tutorials (node API tutorials mainly, etc.)
- Reference (all existing references, broken down by software)

how do you think that aligns with diataxis and what suggestions do you have based on the model on diataxis?

![image](https://github.com/user-attachments/assets/87a50bc8-984c-46df-abcb-872e18f73e2a)

**Comment by Mackenzie-OO7** [comment]
looks good to me. i think it may be helpful to add a sub-section in the learn category that contains the existing overviews of the different modular stack integrations (op, arbitrum, sovereign, others) then include a link to their respective how-to guides.

what do you think?

**Comment by jcstein** [comment]
trying to keep things as minimal as possible so i think integrations belong in how-to-run-X

**Comment by Mackenzie-OO7** [comment]
I'll arrange this in a Miro mind map and share

**Comment by Mackenzie-OO7** [comment]
> I'll arrange this in a Miro mind map and share

![Mind Maps (2)](https://github.com/user-attachments/assets/23560a6d-aa1a-406d-a38f-8de0cf9b8f77)

**Comment by jcstein** [comment]
this looks like a great start to me! thank you for putting this together

**Comment by Mackenzie-OO7** [comment]
> this looks like a great start to me! thank you for putting this together

ty! can I make a draft pr implementing this organization?

**Comment by jcstein** [comment]
sure thing! I would be glad to review that.
