### ISSUE TITLE
Clarify that people should not be relying on free community RPC endpoints for production deployments and they should run their own or rely on service providers with SLAs and provide a list of paid providers

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/docs#1555]

**Comment by jcstein** [comment]
I've pinged NewMetric and Numia to see if they'd like to be listed under the paid providers. Are there any others to be added at the moment?

**Comment by jcstein** [comment]
| Provider | URL |
|--------|--------|
| NewMetric | https://app.newmetric.xyz/start | 
| Numia | |
