### ISSUE TITLE
Consistent casing for light node, bridge node, full node

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#160]
I don't think these should be capitalized when used in paragraphs. Ex:
1. https://github.com/celestiaorg/docs/blob/main/docs/nodes/systemd.md?plain=1#L205=

**Comment by rootulp** [comment]
This issue isn't resolved yet. Ex. https://github.com/celestiaorg/docs/blob/dfebcb60b2623def5fe9b30e16cad11953c600e3/docs/nodes/systemd.md?plain=1#L205=

**Comment by YazzyYaz** [comment]
@rootulp any updates on this issue? Are you going to make a PR?

**Comment by rootulp** [comment]
Is this issue something maintainers want? Given no one else +1'ed this issue or commented, I may be alone in wanting consistent casing.

**Comment by YazzyYaz** [comment]
@rootulp seems that way.
