### ISSUE TITLE
Troubleshooting note for account not found when calling submit_pfd

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#162]
```
[ec2-user@ip-172-31-15-92 celestia-node]$ curl -X POST -d '{"namespace_id": "c14da9d459dc57f5", "data": "4f7a3f1aadd83255b8410fef4860c0cd2eba82e24a", "gas_limit": 60000}'  localhost:26658/submit_pfd
"rpc error: code = NotFound desc = account celestia1krkle0n547u0znz3unnln8paft2dq4z3rznv86 not found"
```

This error is observed if an account hasn't been funded with testnet tokens prior to calling `submit_pfd`. It may help to include a small troubleshooting note under https://docs.celestia.org/developers/node-tutorial#submit-a-pfd-transaction

**Comment by YazzyYaz** [comment]
Great idea, feel free to submit a PR with a fix for this if you like :)
