### ISSUE TITLE
Update diagram of celestia stack in our docs

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/docs#164]
At present we dont have an updated diagram which we show here: https://docs.celestia.org/nodes/bridge-node, as the celestia full storage node was introduced after that diagram was made.

Given the new node type that diagram should be updated and perhaps any changes to the docs due to it (like the general overview of each celestia node sub node type and what it does etc)

**Comment by YazzyYaz** [comment]
The person who made the diagrams @0xMako would need to share the code for them so we can modify it to the new diagrams. The docs at the moment can render draw.io diagrams, but we just need the diagram code.

**Comment by 0xMako** [comment]
@YazzyYaz The diagrams were originally created in Figma, and I've resent the invite to your email. Link to Figma below

https://www.figma.com/file/WOND2LqIkYNhtP3D1P4gwY/Celestia?node-id=0%3A1

We'd love to continue working on this, perhaps as part of the Modular Fellows program!

**Comment by YazzyYaz** [comment]
Closing as we are updating the diagrams separately
