### ISSUE TITLE
docs: use either Hardfork or Network upgrade consistently across docs

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1676]
To clear confusion, use either Hardfork or Network upgrade consistently throughout the documentation. This is also related to #1675.

**Comment by jcstein** [comment]
Thank you for adding the context! Yep, acknowledging that we'll need to align here first.

**Comment by jcstein** [comment]
Voting on poll is leaning toward "Network upgrade" https://celestia-team.slack.com/archives/C01JZFUPG48/p1724260139073369

**Comment by rootulp** [comment]
I'm in favor of network upgrade. FYI we just have to be careful when addressing this issue to not break any existing links to the docs. Or if we break the links, fix them. 

For example the [v2.0.0 release notes](https://github.com/celestiaorg/celestia-app/releases/tag/v2.0.0) link to Lemongrass hardfork.

**Comment by jcstein** [comment]
Good call out. Do you think it would be best practice to leave "Lemongrass hardfork" as is? So as to not break things for that, and going forward, use Network upgrade?

**Comment by jcstein** [comment]
While it is possible, it still feels a little jank, because you have to leave an old page up still. This is the cleanest way in Vitepress to do redirects that I know of: https://github.com/celestiaorg/docs/pull/1542/files

**Comment by rootulp** [comment]
hmm I just tried two alternative way to configure redirects:
1. `router.addRoute` 
2. `rewrites`
but neither worked so agreed that it's kinda jank

**Comment by jcstein** [comment]
yeah, I'm on the fence about what to do so will think about this

https://github.com/celestiaorg/docs/pull/1552 reverted #1542 pretty quickly bc it was so jank 😅

**Comment by jcstein** [comment]
I plan to implement this after v2 is live this week

**Comment by jcstein** [comment]
can you please update the link on [v2.0.0 release notes](https://github.com/celestiaorg/celestia-app/releases/tag/v2.0.0) to "https://docs.celestia.org/nodes/hardfork-process#lemongrass-network-upgrade"?
