### ISSUE TITLE
Remove backlinks in Mamaki testnet guide

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#169]
I'm setting up a consensus full node by following https://docs.celestia.org/nodes/consensus-full-node

which links to https://docs.celestia.org/nodes/mamaki-testnet#setup-p2p-network

the bottom of this section says:

> You can return back to where you left off in the Bridge Node guide [here](https://docs.celestia.org/nodes/validator-node#configure-pruning)

However this section is applicable to consensus full nodes and not just bridge nodes so this backlink is confusing.

This occurs again in the following section https://docs.celestia.org/nodes/mamaki-testnet#quick-sync-with-snapshot

> You can return back to where you left off in the Bridge Node guide [here](https://docs.celestia.org/nodes/validator-node#start-the-celestia-app-with-systemd)

**Comment by YazzyYaz** [comment]
@rootulp want to submit a PR to fix?
