### ISSUE TITLE
Command to check balance assumes celestia-appd is running

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#170]
I funded a wallet following the steps in https://docs.celestia.org/developers/wallet#fund-a-wallet

However I can't query celestia-appd because I don't have it running. This section assumes I have celestia-appd running but I haven't gotten to that step yet.

```
root@rootulp-consensus-full-node:~/celestia-app# celestia-appd q bank balances celestia1w9axzgxkqkznpgwhlp80f4uq9nzm59ry809l7a
Error: Post "http://localhost:26657": dial tcp [::1]:26657: connect: connection refused
```

**Comment by YazzyYaz** [comment]
@rootulp want to submit a PR? All you need to add is `celestia-appd start` prior to the query command.
