### ISSUE TITLE
docs: add op stack walkthrough to docs

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1705]
https://www.youtube.com/watch?v=lOLw4uLX644

**Comment by Mackenzie-OO7** [comment]
@jcstein hi! is this up for grabs?

**Comment by jcstein** [comment]
I think it's fine to be mentioned on the tutorial page

**Comment by Mackenzie-OO7** [comment]
> I think it's fine to be mentioned on the tutorial page

got it👍🏾

**Comment by Mackenzie-OO7** [comment]
> I think it's fine to be mentioned on the tutorial page


sorry i kinda got sidetracked😓. i just opened a pr
