### ISSUE TITLE
Celestia node flags are outdates across the doc

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/docs#175]
In multiple places there is use of `--core.grpc` <host:port> flag that doesn't exist anymore. It needs to be updated to combination of flags: `--core.ip` <host> ,   `--core.grpc.port` <port>

**Comment by renaynay** [comment]
There is a PR open for this here https://github.com/celestiaorg/docs/pull/166

It will be merged once we release

**Comment by YazzyYaz** [comment]
@walldiss you are building from the latest `main` branch.

Follow the docs to build from the correct version https://docs.celestia.org/developers/celestia-node#install-celestia-node

**Comment by renaynay** [comment]
Can we close?
