### ISSUE TITLE
docs: Internal firewall for Celestia 

### ISSUE THREAD

**Issue by GeoddHQ** [celestiaorg/docs#1760]
## Motivation
As the Celestia network grows, it attracts validators from various regions, some of which may have limited network security infrastructure or vulnerabilities to attacks like DDoS and network flooding. Currently, many validators rely on third-party security measures or basic firewall settings, which may not provide sufficient protection against malicious traffic as the network scales. To ensure the resilience and uptime of validator nodes, it is important to implement more robust, node-level security directly on the server infrastructure.

 [FireHOL](https://github.com/firehol/firehol), a lightweight and flexible firewall management tool, allows validators to efficiently handle IP blacklists, traffic filtering, and rate limiting, thereby safeguarding the node from malicious actors. FireHOL leverages iptables and ipsets to manage firewall rules dynamically, enabling validators to block known bad actors using public blocklists and mitigate DDoS attacks by rate-limiting traffic to critical ports. This approach offers a streamlined, low-maintenance solution for validators to enhance node security without relying solely on external protections.

Features to implement
- Traffic filtering and rate limiting to mitigate potential DDoS attacks.
-  Dynamic IP blocking using blacklists Emerging treats
-  Flexible firewall rules that allow only necessary traffic for Celestia node operations.

We apologize for creating a PR before the discussion, which can be seen here #1759 

Best
Geodd

**Comment by GeoddHQ** [comment]
Hi @jcstein 
Can you assign the relevant developers here for further discussion so we can know their thoughts on this matter
Best Regards
Malith

**Comment by jcstein** [comment]
Yes, is this advisable to add to documentation, @celestiaorg/celestia-core ?

**Comment by GeoddHQ** [comment]
Thank you for the review and the feedback and challenging the proposal. You are correct and we agree that relying solely on a central blacklist poses potential issues. However, we believe that node providers should go beyond basic measures and actively contribute to the security. Celestia's use case is particularly unique, and while major cloud providers like AWS or GCP include high security practices, the reality is that most node operators will be using standard bare metal setups, which may not have the same level of built-in security.

It’s important to empower node providers with the knowledge and tools to enhance their server-level security. Encouraging best practices for securing bare metal infrastructure is not just beneficial but necessary, especially in decentralized environments where responsibility for security is distributed. We collaborate with Layer 1 blockchain projects that have successfully implemented internal security mechanisms, Firehol is an   Manager for UFW and iptables, no extra layer anding vulnerabilities. As the team has already closed the issue and we can revisit this maybe in the future 😊
