### ISSUE TITLE
Query to get the latest block on full node.

### ISSUE THREAD

**Issue by shaswatsaloni** [celestiaorg/docs#1778]
Hi, i set up the fullnode for celestia using the command for docker setup

sudo docker run -d -e NODE_TYPE=full -e P2P_NETWORK=celestia -v /node-celestia:/home/celestia ghcr.io/celestiaorg/celestia-node:v0.17.2 celestia full start --p2p.network celestia

i can see the node size is increasing in the logs
Can anyone help me with which ports to be opened to query the node

and what is curl to get the latest block?

**Comment by jcstein** [comment]
can you please ask this in discord?

**Comment by jcstein** [comment]
as example, this is query for latest: `https://rpc-mocha.pops.one/block`
