### ISSUE TITLE
style: fix OG preview images to show up when shared on Twitter

### ISSUE THREAD

**Issue by alex-beckett** [celestiaorg/docs#1793]
Image card for the docs page doesn't show up when the docs is linked on Twitter

<img width="696" alt="Screenshot 2024-11-18 at 2 07 06 pm" src="https://github.com/user-attachments/assets/f1b89f4d-46b4-4b63-862c-7fec51300326">

**Comment by jcstein** [comment]
check with: https://www.opengraph.xyz/url/https%3A%2F%2Fdocs.celestia.org

**Comment by jcstein** [comment]
attempted fix in #1794 and waiting for it to propogate to test on twitter. it's still showing on the site above as metadata being correct
