### ISSUE TITLE
PR preview deployments

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#187]
## Feature request

Reviewers may benefit from seeing a rendered version of the docs at PR review time. 

## Proposal
Next.js has this enabled out of the box but this repo uses Docusaurus. We may be able to get the same benefit by switching from deploying via gh-pages to Vercel. See https://docusaurus.io/docs/deployment#deploying-to-vercel

**Comment by YazzyYaz** [comment]
@rootulp our infrastructure is setup to use GH-Pages atm so I don't think restructuring everything to use Vercel to get a rendered view makes the most sense. I'm happy to explore a GH-Pages options though if one exists.

**Comment by rootulp** [comment]
Yea makes sense. We don't need to move deployment from GH pages to Vercel if maintainers don't need this feature. Feel free to close as not planned.

**Comment by YazzyYaz** [comment]
I mean it's possible but you need to update the Actions YAML files and change the plugins and CNAME configuration.

**Comment by jcstein** [comment]
how can we view the GH pages preview deployments on PRs?

**Comment by jcstein** [comment]
resolved in https://github.com/celestiaorg/docs/pull/275
