### ISSUE TITLE
Tab logo is blurry for docs.celestia 

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/docs#197]
The Logo for https://celestia.org is sharp.
The Logo for https://docs.celestia.org is blurry. 

I am using 104.0 (32-Bit) Firefox with Windows 10.
The same problem exists with IE and Chrome as well. 
![grafik](https://user-images.githubusercontent.com/99758629/186373667-9b1c4000-6e78-4ea3-b62b-34bdf2d6b5ee.png)

**Comment by YazzyYaz** [comment]
Do you want to make a PR to update the favicon.ico to the one from celestia.org @nashqueue?

**Comment by nashqueue** [comment]
Idk. It seems like that is not the problem. celestia.org has the same favicon.ico as the docs. But celestia.org has a bunch of other icons as well. Not sure why one is blurry and the other one not. Do you have the same issue or is it only on my site?

**Comment by jcstein** [comment]
Closing in https://github.com/celestiaorg/docs/issues/197
