### ISSUE TITLE
Update 'Install Golang' section for Raspberry Pi Users

### ISSUE THREAD

**Issue by MichaelCutro** [celestiaorg/docs#199]
When installing Golang on a Raspberry Pi, users that run 'go version' will get '[Cannot Execute Binary File](https://askubuntu.com/questions/1387906/how-to-install-golang-on-ubuntu-server-20-04-lts-cannot-execute-binary-file)' after running the wget command below: 

wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz" 

**This command will do the trick:**

wget "https://golang.google.cn/dl/go1.18.2.linux-arm64.tar.gz"

**I suggest making another section below this one:** 

ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"

**like so:** 

#If you are running Ubuntu Linux 20.04 (LTS) on a Raspberry Pi 

ver="1.18.2"
cd $HOME
wget "https://golang.google.cn/dl/go1.18.2.linux-arm64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf go1.18.2.linux-arm64.tar.gz
rm "go1.18.2.linux-arm64.tar.gz"

**Comment by jcstein** [comment]
confirmed that this works as expected! thank you for this suggestion, @MichaelCutro

## If you are running Ubuntu Linux 20.04 (LTS) on a Raspberry Pi

```ver="1.18.2"
cd $HOME
wget "https://golang.google.cn/dl/go$ver.linux-arm64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-arm64.tar.gz"
rm "go$ver.linux-arm64.tar.gz"```

**Comment by jcstein** [comment]
thank you again @MichaelCutro - this will be resolved in https://github.com/celestiaorg/docs/pull/259
