### ISSUE TITLE
Repertory "how-celestia-works"

### ISSUE THREAD

**Issue by Gunter038** [celestiaorg/docs#201]
Hello. 

Just noticed that you added a repertory "how-celestia-works", within "Concepts" : 

![image](https://user-images.githubusercontent.com/97455701/186879120-49919ca7-e924-41fd-b981-c3ad5e09634c.png)

I don't think that it's useful. It might even add problems, according to me. We just should keep "Concepts"(Navbar), and a homogenous architecture.  

Architecture is already modified here : 

![image](https://user-images.githubusercontent.com/97455701/186878995-c155c4e0-6b51-4853-9753-b894031fd243.png)

What do you think ?

**Comment by YazzyYaz** [comment]
Can you help me understand why it's an issue? I am thinking of adding more directories in the future as to help organize content into more folders. Why is it an issue for translations, maybe it's something we can support you on?

**Comment by Gunter038** [comment]
Hello. @YazzyYaz 

Well, so far the website used to work that way: 
-	Names are given with navbar.
-	Names are given with the sidebar. 

For translations: 

-	Navbar is translated in a json file. 
-	Sidebar is translated by adding a sidebar_label. 

Remark: I think that creating a sub repertory might have an impact on naming. 

Basically, it would create 3 parameters having an impact on naming. (Not 100% sure, I’ll do a crash test). What does happen if we keep the repertory name in English? 

...I'm on it, Ser !

**Comment by Gunter038** [comment]
It works ! We will be able to translate everything !
