### ISSUE TITLE
Suggestion : Reorder Cosmwasm tutorial 

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/docs#210]
This Issue is about the CosmWasm tutorial on Optimint. 

Maybe the contract compiling and optimizing should happen before running the light client and wasmd chain.

Therefore it uses less resources , and the developer experience is faster.  

One Suggestion could be turning the current order: 
...
- CosmWasm Dependencies
- Setup Network Environment
- Contract Deployment
- Contract Interaction
....

To this order: 
...
- CosmWasm Dependencies
- Contract Compiling (with Optimization)
- Setup Network Environment
- Contract Interaction (with Deployment)
....

**Comment by YazzyYaz** [comment]
I don't think it makes sense at the moment because Contract Deployment can be expanded after with smart contract in-depth development. 

At the moment, it shows how to setup a cosmwasm network on your own but can expand to just connecting to an existing cosmwasm existing sovereign rollup.
