### ISSUE TITLE
How is data unavailability induced halting resolved? 

### ISSUE THREAD

**Issue by vinodganesan** [celestiaorg/docs#229]
In your docs (https://celestiaorg.github.io/celestia-specs/latest/rationale/fork_choice_das.html), the light and superlight nodes repeatedly try to download data within an unbonding / weak-subjectivity window, failing which the nodes come to a halt. 

How is this "halting" problem resolved? How are the nodes resumed? Who is responsible? I couldn't find any relevant information anywhere regarding this. Can you please provide some clarity on the same? 

Thanks,
Vinod

**Comment by adlerjohn** [comment]
It's resolved via social agreement.

**Comment by vinodganesan** [comment]
What is a social agreement? Could you please elaborate on the same?

**Comment by adlerjohn** [comment]
See section "Consequences" https://blog.ethereum.org/2014/11/25/proof-stake-learned-love-weak-subjectivity
