### ISSUE TITLE
Document How To Delegate and Undelegate Tokens to Validators

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#233]
Document How To Delegate and Undelegate Tokens to Validators

**Comment by mindstyle85** [comment]
delegate:

`celestia-appd tx staking delegate <validator valoper> <amount> --from <wallet> --chain-id <chain-id>`

undelegate:

`celestia-appd tx staking unbond <validator valoper> <amount> --from <wallet> --chain-id <chain-id>`
