### ISSUE TITLE
Document How To Submit Logs of Your Node

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#239]
For both Consensus and DA Nodes

**Comment by mindstyle85** [comment]
exampes:

```
sudo journalctl -u <your systemd service> -S yesterday > node_logs.txt
sudo journalctl -u <your systemd service> -S today > node_logs.txt
sudo journalctl -u <your systemd service> -n 1000000 > node_logs.txt
```

last one will output 1 million lines, but this task basically depends on how much logs we want and for what (just to verify then really ran their node or something else, and if its even needed)
