### ISSUE TITLE
Clearly details of DA usage

### ISSUE THREAD

**Issue by spartucus** [celestiaorg/docs#278]
From a user's point of view, through which node does my data reach the DA layer, and what specific requirements do I need? I just need to know what should I do when I use Celestia's DA layer feature, preferably with a `hello world` example. The current documentation is not clear enough, do I just need light node, or do I also need celestia-appd? And how to sync light node quickly?

**Comment by jcstein** [comment]
hi @spartucus - thank you for this issue! what do you think of the current node tutorial? it gives an overview of how to run a light node, and how to submit data using the CLI

https://docs.celestia.org/developers/node-tutorial/

**Comment by jcstein** [comment]
I believe this was closed with the addition of a submit-data page in https://docs.celestia.org/concepts/submit-data/ #1009 

please reopen the issue if this isn't the case, thanks!
