### ISSUE TITLE
Broken link to Arabica Devnet

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/docs#342]
Link to Arabica Devnet in the Mamaki Testnet page is broken.

https://docs.celestia.org/nodes/mamaki-testnet/

![Screenshot 2022-12-05 at 12 16 25 PM](https://user-images.githubusercontent.com/132667/205734433-0322e3d1-15be-4624-842e-c40e219225b8.png)

**Comment by jcstein** [comment]
Very bizarre, the links for these links on `nodes/mamaki-testnet` and `nodes/arabica-devnet` are `[Arabica Devnet](./arabica-devnet)` and `Mamaki [here](./mamaki-testnet)`

on an incognito window, I visit https://docs.celestia.org/nodes/mamaki-testnet/ and when I first click `Arabica Devnet` it errors, but if I visit the Arabica page, then go back to Mamaki from the link on Arabica, it works. Then, from Mamaki to Arabica works. any idea why?

![2022-12-08 11 53 22](https://user-images.githubusercontent.com/46639943/206517001-2da04c07-86b5-4bc3-ae64-5400a9fa6093.gif)

**Comment by jcstein** [comment]
Perhaps, yeah, did you repro locally or in browser? does it persist or go away when you go to the arabica page and back through the backlinks?

**Comment by tuxcanfly** [comment]
Yeah I just tried in a browser and the issue _not_ persistent, once I've visited the arabica page, it goes away 🤷🏽

**Comment by jcstein** [comment]
🤷 same, but after a hard refresh, it happens again. It may be worth us making an issue on Docusaurus

**Comment by jcstein** [comment]
https://github.com/facebook/docusaurus/issues/8499

**Comment by jcstein** [comment]
closing this as I think we resolved the issue with links and old pages showing https://github.com/celestiaorg/docs/commit/829569b6b58c0c3032ef1142e5a72e3a33047cbf 

<img width="1562" alt="Screenshot 2023-01-16 at 10 26 37 PM" src="https://user-images.githubusercontent.com/46639943/212803445-1502a878-6164-4436-a8c7-e1bb1b0531e3.png">
