### ISSUE TITLE
bug: incorrect Big O notation

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#348]
## Context

https://github.com/celestiaorg/docs/pull/345 and 

https://github.com/celestiaorg/docs/blob/26e11606abd62f52a52e9d9da8f5288a24216cdc/docs/concepts/how-celestia-works/data-availability-layer.md?plain=1#L90-L96

## Problem

An earlier paragraph states the original data is O(n^2) so this is inaccurate:

> the original data, i.e., O(n) bytes.

**Comment by jcstein** [comment]
thank you @rootulp 🙌  will review PR you make or make one myself in 2023
