### ISSUE TITLE
docs - list of links returning 404's

### ISSUE THREAD

**Issue by stavares843** [celestiaorg/docs#355]
| Status  | URL | Source link |
| ------------- | -------------     | ------------- |
| 404 Not Found  | https://docs.cosmos.network/master/modules/bank/  | https://docs.celestia.org/developers/wordle-module/  |
| 404 Not Found  | https://docs.cosmos.network/master/building-modules/messages-and-queries.html | https://docs.celestia.org/developers/wordle-messages/  |
| 404 Not Found  | https://docs.cosmos.network/master/basics/accounts.html  | https://docs.celestia.org/developers/integrate-celestia/  |
| 404 Not Found  | https://docs.cosmos.network/master/building-modules/keeper.html | https://docs.celestia.org/developers/wordle-keeper/  |
| 404 Not Found  | https://docs.cosmos.network/master/modules/  | https://docs.celestia.org/developers/gm-rollmint/  |
| 404 Not Found  | https://docs.cosmos.network/master/architecture/adr-043-nft-module.html  | https://docs.celestia.org/developers/gm-rollmint/  |
| 404 Not Found  | https://docs.celestia.org/developers/optimint  | https://docs.celestia.org/community/cohort-one-content/  |

**Comment by YazzyYaz** [comment]
Looks like cosmos website moved from master to main, I'll make a fix

**Comment by stavares843** [comment]
🔨
