### ISSUE TITLE
Update Rollmint Docs to Not Use Alice/Bob Keys from Ignite

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#362]

**Comment by jcstein** [comment]
from Javed:
this page suggests running `recipesd  tx recipes create-recipe` with `--from alice` but it looks like we're creating a key with name `recipes-key` in `init.sh` I tried running with `--from recipes-key --keyring-backend=test`  and it worked, as expected.

https://github.com/celestiaorg/docs/blob/04474a4dcb0213f62092f44a32e4cb3acd77a33e/docs/developers/celestia-node-key.mdx - found reference here, but it doesn't seem to be a part of the recipes tutorial

this is where `recipes-key` is coming from: https://github.com/celestiaorg/devrel-tools/blob/main/recipes/init.sh#L5

**Comment by jcstein** [comment]
done here https://github.com/celestiaorg/docs/pull/380/commits/dc74d1d7052e3cae26b98bc19bef9e01e77ec06e
