### ISSUE TITLE
update node api docs to include fee parameter for transaction broadcasts

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/docs#363]
https://github.com/celestiaorg/celestia-node/pull/1484 introduces the following changes to the gateway requests:

All transaction endpoints now have a `"fee"` key needed in the JSON request. An example value for this can be `2000`. This includes the following endpoints:

- [x] SubmitPayForData
- [x] Transfer
- [ ] Delegate
- [ ] BeginRedelegate
- [ ] Undelegate
- [ ] CancelUnbondingDelegation

**Comment by jcstein** [comment]
thank you @distractedm1nd - I don't think we have anything for Delegate, BeginRedelegate, Undelegate, CancelUnbondingDelegation have anything in the docs cc @YazzyYaz
