### ISSUE TITLE
Clarify bandwidth requirements

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/docs#42]
There's no internet service in the world measured as "GB of input-output."

1. Specify bandwidth in Mbps or Gbps
2. Specify up and down separately

**Comment by YazzyYaz** [comment]
Hi @renaynay @Bidon15 @Wondertan @liamsi do you have any context on specified bandwidth for running Celestia Node?

**Comment by Wondertan** [comment]
These are the right corrections. Unfortunately, we don't have the exact numbers to report right now. We can only recommend a 1 Gbps bandwidth(with legroom) requirement for down and 100Mbps for up.
