### ISSUE TITLE
Wordle example compilation errors

### ISSUE THREAD

**Issue by itamarreif** [celestiaorg/docs#422]
When following the [`wordle` Rollmint example](https://docs.celestia.org/category/wordle), the following compilation errors occur:

1. `x/wordle/keeper/msg_server_submit_wordle.go:52:31: undefined: crypto`
2. `cmd/root.go:306:65: undefined: server.FlagIAVLFastNode`

The second can be solved the same was as in the [`gm` Rollmint example](https://docs.celestia.org/developers/gm-query/#start-your-sovereign-rollup)

**Comment by itamarreif** [comment]
Solution for the first problem:
https://github.com/Manav-Aggarwal/wordle/blob/main/x/wordle/keeper/msg_server_submit_wordle.go#L14

Seems this line is missing from the `SubmitWordle` blob in the [`Keeper` section](https://docs.celestia.org/developers/wordle-keeper#submitwordle-function) of the `wordle` example.

**Comment by jcstein** [comment]
I'm experiencing similar behavior, checking with team to see if we need to change versions for this tutorial.

Output: https://app.warp.dev/block/zFexC1tERV0q5sAspJBuQL

**Comment by jcstein** [comment]
### Versions

```bash
Ignite CLI version:	v0.25.2
Ignite CLI build date:	2022-11-21T18:08:22Z
Ignite CLI source hash:	8888014f4cc05f9c92119200f57cad5080d42a3e
Cosmos SDK version:	v0.46.6
Your OS:		darwin
Your arch:		arm64
Your Node.js version:	v19.2.0
Your go version:	go version go1.19.1 darwin/arm64
Your uname -a:		Darwin Joshs-MacBook-Air.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112 arm64
Your cwd:		/Users/joshstein/wordle
Is on Gitpod:		false
```
