### ISSUE TITLE
Add root-level `.markdownlint.yaml`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#457]
[optional] it may be beneficial to introduce a root-level `.markdownlint.yaml` like https://github.com/celestiaorg/celestia-app/blob/main/.markdownlint.yaml so that developers who run `yarn run lint` locally have the same rules applied as the ones running in CI.

Suggested by @rootulp

**Comment by gulshanpr** [comment]
@jcstein I want to work on this issue, can you assign me this?
