### ISSUE TITLE
Translations - Issue 1

### ISSUE THREAD

**Issue by Gunter038** [celestiaorg/docs#467]
Hello ! @YazzyYaz and @jcstein ! 

As we were talking about, the following commands don't work in translations.md. 

```sh
git clone https://github.com/celestiaorg/docs.git
cd docs
yarn
# This command creates updated files, pushes it to crowdin and
# pulls in all latest approved translations
yarn crowdin:sync
# Now you can build your specific translation locally. For example
# for Mandarin, you use `zh`
yarn run start -- --locale zh
```

We are not able to run a translated version of the website on our laptop. 

Have a nice week!

**Comment by YazzyYaz** [comment]
@Gunter038 can you show me the error you see?

**Comment by Gunter038** [comment]
So, when I run : yarn crowdin:sync

I get this : 

![image](https://user-images.githubusercontent.com/97455701/218856510-029dd8e6-82aa-4452-97df-105798d88cec.png)

Then when I run : yarn run start -- --locale zh

![image](https://user-images.githubusercontent.com/97455701/218857729-93d60d56-402a-4292-b7f0-2c48ad6fe3a3.png)

And the website is still in English. 

![image](https://user-images.githubusercontent.com/97455701/218860207-cb18084a-65c1-4c25-bac3-3ed040018a41.png)

Same thing happening with French. 

So I don't know if it's related with creating a specific API token just with the right to upload a translation or with creating a static version of the website.

**Comment by Gunter038** [comment]
I used the git clone command, so it should be the main. 

French is added in the site config, it should be working.

**Comment by jcstein** [comment]
aren't you trying to test Chinese, not french?

> yarn run start -- --locale zh

**Comment by Gunter038** [comment]
Yes but I Also tried with french.

**Comment by jcstein** [comment]
can you please link me to the branch you're working off of so i can try to reproduce? ty!

**Comment by jcstein** [comment]
I don't have the crowdin API token, so cannot test out locally

https://app.warp.dev/block/fpTB3RNKh98P4AJiSjGOSb

**Comment by Gunter038** [comment]
Well, I am working on my laptop, and I clone the repo. 

git clone https://github.com/celestiaorg/docs.git

If you want to generate a static version of the website on your laptop, you should run yarn build.

**Comment by Gunter038** [comment]
> 

We used to work that way. Actually, I think that regarding translations, reviewers should be able to run the website on their laptop to avoid bugs and test their translations.

**Comment by jcstein** [comment]
I only verified that starting it in `zh` works. what is the file path to the page you're talking about? if you made the changes locally on your machine, I will not see them on `celestiaorg:main`, which is what I cloned from

**Comment by Gunter038** [comment]
https://github.com/celestiaorg/docs/blob/main/docs/community/calendar.md

Basically we want reviewers to be able to run the website and import translations from Crowdin, to spot their mistakes, and also bugs breaking the website. 

Changes were made on Crowdin.

**Comment by jcstein** [comment]
Do they need the API key to test it out? Do I need one to test this successfully?

When I run crowdin sync this is part of the output:

```
❌ Configuration file is invalid. Check the following parameters in your configuration file:
        - Required option 'api_token' is missing
```

I made a [PR](https://github.com/celestiaorg/docs/pull/470) to update Docusaurus, and it looks like we also have to bump Crowdin version.

However, after doing that on the [PR's branch](https://github.com/celestiaorg/docs/tree/jcs/docusaurus-version), I started again in `zh` and can't see that page in Chinese, just the headings are translated.
<img width="847" alt="Screenshot 2023-02-15 at 11 01 24 AM" src="https://user-images.githubusercontent.com/46639943/218996072-9640ba88-4434-4a1e-b8e6-15a35cec29e2.png">

I started in `fr` and can not see it in french, it is still in english, headings are also translated
<img width="847" alt="Screenshot 2023-02-15 at 11 03 17 AM" src="https://user-images.githubusercontent.com/46639943/218996523-76dbaf44-9009-4dec-8ba4-01e91a407a56.png">

I suspect the translations aren't being pulled, because I do not have the API key?

**Comment by Gunter038** [comment]
2 hypothesis : 
- We need an API key. 
- We need to generate a static version of the website. We used to have this issue and I fixed it by using yarn build to avoid this problem. 

It is normal to have pre-translated stuff, as French and Chinese Modules pre-translate this.

**Comment by jcstein** [comment]
I am going to see what @YazzyYaz thinks here, as he is more familiar with Crowdin + Docusaurus integration

**Comment by Gunter038** [comment]
Hey @jcstein and @YazzyYaz ! 

I might have found something. I will conduct a crash test. 
It seems that we can avoid issues regarding API tokens by using Crowdin CLI in a laptop.

**Comment by Gunter038** [comment]
Still have to conduct several tests.... But I might have found an easy way : 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/97455701/220762016-aa2a3027-a586-4ad4-a57f-ced3426e489c.png">

**Comment by jcstein** [comment]
I'm interested to hear more about what you've found! 🎉

**Comment by Gunter038** [comment]
Actually it's very dumb and very simple ahaha. 
I am just downloading the translations from Crowdin directly on the website, adding them to a folder and modify the parameters of the website.

**Comment by jcstein** [comment]
oh nice, hmm. the odd thing that happened for me was that it started fine once in Chinese, but then the next time I started the translations didn't show up 🤷 I did not record the steps, so there may have been a difference that caused this

**Comment by Gunter038** [comment]
Mhhh maybe the use of an API token ?

**Comment by jcstein** [comment]
I didn't have one though 😅

**Comment by Gunter038** [comment]
Okay, are you sure that you didn't only get pre-translated stuff by the module? 

Regarding Spanish, at the moment we have several issues, like this one for instance : 

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/97455701/221015432-3ce125a5-61e2-4abd-846e-8638fec88910.png">

**Comment by jcstein** [comment]
reopening this to re-add support for i18n
