### ISSUE TITLE
Logo should be full logo with typeface

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/docs#468]
![celestia_docs_purple](https://user-images.githubusercontent.com/5038597/218749412-97f406c3-af8d-42bf-859b-b2be9a24c06a.svg)

Borders may need cropping, and/or converting to png.

**Comment by jcstein** [comment]
This looks great - will add tomorrow

**Comment by Gunter038** [comment]
I will add it to Crowdin also !

**Comment by jcstein** [comment]
I think that we may need to either:
- increase the size of this logo entirely in the CSS (which may not work well on mobile)
- increase the height of `CELESTIA * DOCS` to make it fill the space better
![Uploading Screenshot 2023-02-15 at 10.19.01 AM.png…]()

**Comment by musalbas** [comment]
As mentioned in first post, the first step should be to crop the whitespace padding in the provided svg (and convert it to png). This should make the logo bigger

**Comment by musalbas** [comment]
Here:
![celestia_docs_purple](https://user-images.githubusercontent.com/5038597/219012149-44b4e646-2d79-4f16-9d5f-4af3de33e61a.png)

**Comment by jcstein** [comment]
done as svg, thanks again. looks much better
