### ISSUE TITLE
Explain Why Validators Need to Run A Bridge Node

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#48]
Explain the need for validators to also need a bridge node.

**Comment by YazzyYaz** [comment]
cc @renaynay @Wondertan @Bidon15

**Comment by renaynay** [comment]
@YazzyYaz in what format would you like for us to do this? Would you like an explanation here that you will turn into docs or would you like for us to write the doc?

**Comment by YazzyYaz** [comment]
We would need an explanation, here is fine. I imagine we need to add it both to the tutorial guide on running a node and maybe in the overview section.

I can help you folks work on one if we want to draft something in Google Docs first.
