### ISSUE TITLE
Use same favicon as https://blog.celestia.org/favicon.png (may require converting to .ico?)

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/docs#482]
For consistency as logo is purple on docs - also the current favicon looks pixelated because it's 16x16 the browser upscales it. If it needs to be converted to .ico it should be a bigger resolution than 16x16

Differences
* non-pixelated purple (what docs should have)
* non-pixelated black
* pixelated black (the docs rn)

![image](https://user-images.githubusercontent.com/5038597/220728759-d969b855-70e5-44ae-9d67-603cdd3e910f.png)

**Comment by jcstein** [comment]
Used [favicon.io](https://favicon.io) to swap it out ✔️

**Comment by jcstein** [comment]
for future use:
[favicon_io.zip](https://github.com/celestiaorg/docs/files/10816032/favicon_io.zip)

**Comment by jcstein** [comment]
<img width="62" alt="Screenshot 2023-02-23 at 3 30 10 PM" src="https://user-images.githubusercontent.com/46639943/221022990-60ebd65f-bab2-4ff7-874c-a1a69774682f.png">
