### ISSUE TITLE
nodebuilder/node.go:95 starting light Node: header/p2p: failed to open a new stream: failed to find peers

### ISSUE THREAD

**Issue by laohe-adam** [celestiaorg/docs#495]
I got this erro when i try to running the light node in my liunx (22.04LTS)
<img width="940" alt="68081a7a627b536e1291010952b1760" src="https://user-images.githubusercontent.com/105530519/222135639-152552a8-ea51-4651-b961-be48ebffac06.png">
[图片][图片]

**Comment by jcstein** [comment]
what version are you running this on?
