### ISSUE TITLE
Update lifecycle of a celestia-app transaction

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#502]
## Context

https://docs.celestia.org/concepts/how-celestia-works/transaction-lifecycle/

## Problem

A few things have been renamed since this diagram was originally created.

## Proposal

Current | Proposed
--- | ---
![tx-lifecycle-9c80bbe1c320bc02c466665bd873169a](https://user-images.githubusercontent.com/3699047/223844848-a7dd2310-352f-4f8e-94ec-94193bac9436.png) | ![tx-lifecycle-9c80bbe1c320bc02c466665bd873169a](https://user-images.githubusercontent.com/3699047/223844675-889fe8eb-c341-4e53-a652-a5672163843b.jpeg)

**Comment by jcstein** [comment]
passed this on to Alina!

**Comment by jcstein** [comment]
How's this look @rootulp?

![image](https://user-images.githubusercontent.com/46639943/228597960-e4586f4e-99f5-45ba-ae0c-5635fb778952.png)

**Comment by jcstein** [comment]
One nit, should it be `PayForBlob` or `PayForBlobs`?

**Comment by rootulp** [comment]
It can be either. Slight preference for `PayForBlobs` b/c that's what a user will use in CLI

<img width="1155" alt="Screenshot 2023-03-29 at 9 52 14 PM" src="https://user-images.githubusercontent.com/3699047/228652058-73b59e1f-ae5f-4bab-95de-6082ce09517a.png">
