### ISSUE TITLE
Provided list of peers are have maxed out connections

### ISSUE THREAD

**Issue by smuu** [celestiaorg/docs#504]
https://docs.celestia.org/nodes/celestia-node/

The peers have maxed out connections, making it hard to connect to the network with a new consensus node. As it is a public dev net, community members should contribute to the peer list. Adding a section to the setup page asking people to add their peers via a PR motivates community members to contribute.
Maye also write a message to the community discord to get started quickly.

**Comment by jcstein** [comment]
Is this meant for `celestia-node` instead? @smuu

**Comment by smuu** [comment]
> to clarify, [here](https://docs.celestia.org/nodes/blockspace-race/#rpc-endpoints) or [here](https://github.com/celestiaorg/networks/blob/master/blockspacerace/peers.txt) @smuu ?

Back then, BSR was not started yet. I tried it with Mocha. See [here](https://github.com/celestiaorg/networks/tree/master/mocha).

**Comment by jcstein** [comment]
in the process of writing #841, I encountered the same thing. endless search for peers

![https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExN2tpZ3VkdXZrcWs2emgyZzRhY3Z2M2g4bTVqZnZ4NDVzcWx3MTBlOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/OtQyHyvGZabEDAERq6/giphy.webp](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExN2tpZ3VkdXZrcWs2emgyZzRhY3Z2M2g4bTVqZnZ4NDVzcWx3MTBlOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/OtQyHyvGZabEDAERq6/giphy.webp)
