### ISSUE TITLE
Add instructions for submitting and getting data from Celestia for testnet

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/docs#53]

**Comment by YazzyYaz** [comment]
Guide must able to tell developers how to submit data transactions to Celestia and how to get data from Celestia by namespace.

**Comment by YazzyYaz** [comment]
Wait for this to be merged https://github.com/celestiaorg/celestia-node/pull/658

**Comment by YazzyYaz** [comment]
PR: https://github.com/celestiaorg/docs/pull/68
