### ISSUE TITLE
Consider consolidating consensus and validator pages on docs

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/docs#556]

**Comment by jcstein** [comment]
Hm, do we want to leave these node types separate as one is for app and one is for node?

**Comment by rootulp** [comment]
https://docs.celestia.org/nodes/validator-node/ and https://docs.celestia.org/nodes/consensus-full-node/ both use celestia-app.

**Comment by jcstein** [comment]
I think my comment above is a good example of the confusion introduced by naming different node types:
- celestia-node light node
- celestia-node full node
- celestia-node bridge node
- celestia-app consensus validator node
- celestia-app consensus full node

The celestia-app consensus full node and celestia-node full node are often both referred to as "full nodes" In an effort to clear confusion, I opened #843 and #844 to rename the celestia-app consensus full node in documentation to match the GitHub repository of celestia-app. The "consensus full node" is now referred to as "full consensus node"

I will still consider consolidating the validator and consensus full node pages, but am not sure exactly how so will revisit in the coming weeks

**Comment by jcstein** [comment]
<img width="299" alt="scrot 2023-09-29 at 10 09 08 PM" src="https://github.com/celestiaorg/docs/assets/46639943/1cd36bad-b70c-4586-8d4c-9003d0be3287">
