### ISSUE TITLE
Translate Docs to Mandarin

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#58]
Do a documentation translation to Mandarin

**Comment by Ting2005** [comment]
Hey, I'm willing to translate for the Chinese community. Do I need to study docusaurus?

**Comment by Gunter038** [comment]
Hello Ting ! Yaz and I decided to use crowdin to do the translations. It's easier to use. Celestia docs is available here : https://crowdin.com/project/celestia-docs . It's not over yet, I still have to add some informations and add a "procedure". But you can start the translation. I can add your langage. Mandarin is called "Chinese" in crowdin. Which language do you want : Traditional chinese or Simplified chinese ? You will be able to do the translation, then. Feel free to talk to me in discord (i'm gunter).

**Comment by Ting2005** [comment]
> 婷你好！Yaz 和我决定使用 crowdin 进行翻译。它更容易使用。Celestia 文档可在此处获得：[https](https://crowdin.com/project/celestia-docs) ://crowdin.com/project/celestia-docs 。还没完呢，我还是要补充一些资料，加个“程序”。但是你可以开始翻译。我可以添加你的语言。普通话在crowdin中被称为“汉语”。您想要哪种语言：繁体中文还是简体中文？那你就可以翻译了。随意与我不和谐地交谈（我是枪手）。

Simplified Chinese, so how do I start?

**Comment by Gunter038** [comment]
Hey, @YazzyYaz. I think that we can close issues related with translations.
