### ISSUE TITLE
Add note about full-consensus-node storage requirements

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#648]
https://github.com/celestiaorg/docs/pull/641#discussion_r1164568713

**Comment by AnmolSirola** [comment]
@jcstein Can I work on this issue ?

**Comment by jcstein** [comment]
of course! assigned to you

**Comment by AnmolSirola** [comment]
@jcstein Can you tell me in which file do I need to make the required changes?

**Comment by jcstein** [comment]
https://github.com/celestiaorg/docs/blob/main/docs/nodes/full-consensus-node.md
