### ISSUE TITLE
French translation doesn't work

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#649]
I would expect https://docs.celestia.org/fr/ to display text in French but all the text appears in English

I got to this page via

<img width="208" alt="Screenshot 2023-04-13 at 3 57 05 PM" src="https://user-images.githubusercontent.com/3699047/231869314-c8b17d4b-3e95-4f70-86ed-0f9a55f5f02a.png">

**Comment by Gunter038** [comment]
Hey @rootulp ! We decided to unaprove french at the moment, in order to conduct a crash test not compromising the website. So that's normal.

**Comment by rootulp** [comment]
Do you think the French option should be removed from the language selector? Given that only leaves English, maybe the language selector should be removed entirely.

**Comment by Gunter038** [comment]
Maybe yeah, then I would be able to approve it again.

**Comment by iabudumilionerom** [comment]
Delet French language, because during 2 months it's not working, it's not pro bro ;)
