### ISSUE TITLE
enable a CI linter on this repo to auto-format .mdx files

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#676]
From #675

**Comment by gulshanpr** [comment]
@jcstein I came up with this solution to add prettier in the `package.json` as devDependencies and extend the `lint.yml` workflow with `yarn run format` and this format is a defined script in `package.json` as `"format": "prettier --write '**/*.mdx'"` by doing this It auto format the code.
do you have any other solution?, if not can i work on this?

**Comment by jcstein** [comment]
this sounds like a good solution to me! feel free to open a PR, i've assigned it to you

**Comment by gulshanpr** [comment]
can you review it and suggest me what should i do more?

**Comment by gulshanpr** [comment]
@jcstein , while working on another issue I closed and deleted some head, can you review it

**Comment by jcstein** [comment]
hi, no problem! will review
