### ISSUE TITLE
Add Rollups overview page

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#686]

**Comment by Mackenzie-OO7** [comment]
@jcstein can I work on this?

**Comment by jcstein** [comment]
hi @Mackenzie-OO7 - absolutely! it should be similar to this overview page of the "Developers" category, for example: https://docs.celestia.org/developers/overview/

**Comment by Mackenzie-OO7** [comment]
> hi @Mackenzie-OO7 - absolutely! it should be similar to this overview page of the "Developers" category, for example: https://docs.celestia.org/developers/overview/

Alright! Noted
