### ISSUE TITLE
Clarify flags of start node command to improve UX

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#709]
Here: https://docs.celestia.org/nodes/light-node/#start-the-light-node

It is not 100% clear from the instructions what is needed to fill in the command:

```bash
celestia light start --core.ip <ip-address> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network blockspacerace
```

**Comment by gulshanpr** [comment]
> Here: https://docs.celestia.org/nodes/light-node/#start-the-light-node
> 
> It is not 100% clear from the instructions what is needed to fill in the command:
> 
> ```shell
> celestia light start --core.ip <ip-address> --gateway --gateway.addr <ip-address> --gateway.port <port> --p2p.network blockspacerace
> ```
Can you explain this bit more?

**Comment by jcstein** [comment]
I'd just like to add explainers on each of the flags, which can be found by using:

```
celestia light start --help
```

**Comment by jcstein** [comment]
done in #1168
