### ISSUE TITLE
Make sidebar collapsible on screen sizes larger than small/md

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#718]
<img width="1140" alt="scrot 2023-05-04 at 10 47 28 AM" src="https://user-images.githubusercontent.com/46639943/236244177-92721a13-42d6-4ea2-8fa5-b0b08228f507.png">

**Comment by Sdaewa** [comment]
Hi there! Can I get this assigned?

**Comment by jcstein** [comment]
Yes @Sdaewa! done 😄 please let me know if you have any questions

**Comment by Sdaewa** [comment]
Hi! I have tried but cannot implement it. I will unassign the issue.

**Comment by Wholesomebruh** [comment]
Hey @jcstein it seems to me like it's already resolved as I am able to collapse it without making any changes. Please correct me if I'm wrong.

**Comment by jcstein** [comment]
this would be to add a feature to be able to manually collapse it

**Comment by Wholesomebruh** [comment]
That's what I'm saying that I am able to collapse it manually.

**Comment by Wholesomebruh** [comment]
![image](https://github.com/celestiaorg/docs/assets/109906215/1078e03c-8cdd-4fd4-88e7-5f9aaacfa589)
You want it to be like this?

**Comment by jcstein** [comment]
yep! essentially. i was thinking a little hamburger at the top left

**Comment by Wholesomebruh** [comment]
Everything like small/mid screen , implemented on large screen?

**Comment by Wholesomebruh** [comment]
@jcstein  custom navbar hasn't been applied to docusaurus official version yet , custom made elements can disrupt normal flow. Assign this to me so that I can implement the sidebar collapsing as shown in the screenshot.

**Comment by jcstein** [comment]
hm, so the entire sidebar as a button is a little too big i think. i'm thinking more of something like what is on here

https://nextra.site/docs/docs-theme/start

<img width="967" alt="Screenshot 2023-06-30 at 1 21 45 PM" src="https://github.com/celestiaorg/docs/assets/46639943/0ca3ab25-2d2c-485b-991a-2692f5ff05ad">

<img width="1822" alt="Screenshot 2023-06-30 at 1 22 32 PM" src="https://github.com/celestiaorg/docs/assets/46639943/18e3f98a-e929-4c51-b060-a683857e6570">

**Comment by jcstein** [comment]
so, this is to give user option, specifically

**Comment by Wholesomebruh** [comment]
Hey @jcstein ,please review the pull request #856

**Comment by Wholesomebruh** [comment]
Hey, what's causing the PR to fail as there is just 3 line changes in 1 file?

**Comment by jcstein** [comment]
Resolved in #856

**Comment by Wholesomebruh** [comment]
Thank you very much for resolving. Looking forward for more contributions.
