### ISSUE TITLE
Add descriptions and sidebar labels to existing pages

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#720]
This is to improve the previews of pages in categories, add the following at the top of `.md` and `.mdx` files:

```md
---
sidebar_label: Example sidebar label
description: A concise description of the page
---
```

If the page title is different than what you'd like to show in the sidebar, use a different sidebar label. 

<img width="1028" alt="scrot 2023-05-04 at 10 50 09 AM" src="https://user-images.githubusercontent.com/46639943/236245837-f99ec266-0a10-4104-8349-29dc17596caa.png">

**Comment by alexgorunescu97** [comment]
I would like to work on this. Can you assign it to me?

**Comment by alexgorunescu97** [comment]
Sure. So just to make sure, this only applies for pages under the '/category' url?
