### ISSUE TITLE
Document that PFD endpoint accepts up to 2 MB under default settings

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#79]
The Node `submit_pfd` API endpoint must indicate it can accept up-to 1 MB size for a data submission

**Comment by evan-forbes** [comment]
I actually think we should just change the default setting of the tendermint config, but whatever we do we should probably document the size of the messages that are allowed.

We might want to discuss how this is determined. Something along these lines https://github.com/celestiaorg/lazyledger-app/blob/52af4ac7ba4797d76d5ebfc384e3edcf36198546/x/payment/types/payfordata.go#L128-L135

**Comment by YazzyYaz** [comment]
@evan-forbes any resolution on this? Did we decide on a default setting?
