### ISSUE TITLE
Outdated `namespace_id` example

### ISSUE THREAD

**Issue by rkdud007** [celestiaorg/docs#811]
<img width="896" alt="Screenshot 2023-06-10 at 1 09 57 PM" src="https://github.com/celestiaorg/docs/assets/76558220/564e86a9-0bd9-4f9d-af36-df850719665a">
<img width="659" alt="Screenshot 2023-06-10 at 1 10 24 PM" src="https://github.com/celestiaorg/docs/assets/76558220/fc6c41eb-4946-4695-81fd-79afd029b7d6">

"unsupported namespace id length: id [12 32 77 57 96 15 221 211] must be 28 bytes but it was 8 bytes" is not reflected on docs

**Comment by jcstein** [comment]
hi, thank you for the issue! this will be resolved in https://github.com/celestiaorg/docs/issues/785
