### ISSUE TITLE
Add example for node rpc state Transfer 

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/docs#853]
Should be in here: https://docs.celestia.org/developers/node-tutorial/#more-examples

**Comment by jcstein** [comment]
okay, so with this [transaction](https://explorer-arabica-9.celestia-arabica.com/arabica-9/tx/C4F215833C4C041F006A6778DF0E24C15FD22D13D6BC05994E91400BC4D7D1FC), generated from:

```bash
celestia rpc state Transfer celestia1c425ckmve2489atttx022qpc02gxspa29wmh0d 100000 8000 80000
```

I will use this as the example for now, but after recent discussions around gasFee/gasLimit, I'm not sure what is best! any ideas?
