### ISSUE TITLE
update mocha endpoints

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#876]
Removed in #875 to prevent users attempting to use an outdated RPC. please make a PR when you have your new endpoints ready @jim-counter 🙌

**Comment by jim-counter** [comment]
Hey Josh, I can still see the counterpoint endpoints on the live website. Our node has been updated to mocha-3 so what's out there currently is accurate.

**Comment by jcstein** [comment]
sounds good! closing this, sorry for the delay here :)
