### ISSUE TITLE
Arabica tab for full consensus node setup the p2p networks

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#912]
## Context

I'm trying to set up a full consensus node on Arabica

## Problem

There is no Arabica tab on https://docs.celestia.org/nodes/full-consensus-node/#setup-the-p2p-networks

## Proposal

Add an Arabica tab

**Comment by jcstein** [comment]
great idea and thank you for this. overlooked it bc no validators for arabica bc POA. confirming that the process is the same? aside from the naming

**Comment by rootulp** [comment]
Yea I expect the process to be the same aside from name of the network / chain-id in commands.
