### ISSUE TITLE
Consider removing Blockspace Race tabs

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#917]
Since Blockspace Race is over, I wonder if we should consider removing the tabs for Blockspace Race from

<img width="1001" alt="Screenshot 2023-07-21 at 6 08 21 PM" src="https://github.com/celestiaorg/docs/assets/3699047/6547ae85-2217-4d0a-ae18-79e320a9aa35">

**Comment by jcstein** [comment]
yes, we're planning to repurpose these for mainnet -- maybe in the meantime I will comment these sections out cc @YazzyYaz for vis
