### ISSUE TITLE
Add More Buttons to Landing Page of Docs

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/docs#95]

**Comment by xxxxxchan** [comment]
# The simple design of a document page UI:
### Divided into three modules:
-  Overview
- How to get started
- Contribution
### hope it helps

![Celestia Docs UI](https://user-images.githubusercontent.com/82381764/170822660-e4cf29de-39fb-4beb-b5fe-be14aa316b0b.png)

**Comment by Ting2005** [comment]
nice！

**Comment by Ting2005** [comment]
cool
