### ISSUE TITLE
Update the docs for `--evm-address`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#968]
## Context

celestia-app [v1.0.0-rc12](https://github.com/celestiaorg/celestia-app/releases/tag/v1.0.0-rc12) contains a breaking change that removes the `--evm-address` flag. 

## Problem

The docs still reference the `--evm-address` flag. See https://docs.celestia.org/nodes/validator-node/#setup-qgb-keys

## Proposal

Update the docs to remove the `--evm-address` flag and describe the new mechanism for sending a tx to register a validator's EVM address. See https://github.com/celestiaorg/celestia-app/commit/8428940f9df4f0411bd5d0385a244f87ec743aa6

We may need to preserve the docs for the `--evm-address` flag for releases prior to v1.0.0-rc12. Defer to @SweeXordious

**Comment by SweeXordious** [comment]
Thanks, I guess we can just update the docs... the `v1.0.0-rc12` will not really be used for anything useful or mainnet related

**Comment by jcstein** [comment]
thanks for the issue. i plan to make a PR for this (hopefully today EDT) and based on @SweeXordious guidance above, may just overwrite old versions

**Comment by SweeXordious** [comment]
cc @evan-forbes What do you think? does it make to just forget about the `--evm-address` flag?

**Comment by evan-forbes** [comment]
I think we can yeah



> as far as I know, the v1.0.0-rc12 will not really be used for anything useful or mainnet related

@SweeXordious do you just mean this isn't the final release? since something very similar to it will be used for mainnet, I think updating the docs with it makes sense but perhaps I'm missing something obvious?

**Comment by jcstein** [comment]
i think it is: should we keep the old instructions accessible in docs? those prior to v1.0.0-rc12?

**Comment by rootulp** [comment]
>  should we keep the old instructions accessible in docs? those prior to v1.0.0-rc12?

IMO yes until public facing testnets (specifically Mocha) upgrade to a celestia-app release > v1.0.0-rc12

**Comment by jcstein** [comment]
<img width="332" alt="nniiiiiice 2023-08-22 at 15 51 40" src="https://github.com/celestiaorg/docs/assets/46639943/dcb053c9-cc13-4823-b3f9-c1602b1f67e4">

**Comment by jcstein** [comment]
as I was doing the above, it began to make more sense why you all have suggested to combine validator + full pages #556
