### ISSUE TITLE
add docusaurus.io documentation link in readme.md file and what is docusaurus.io ?

### ISSUE THREAD

**Issue by manzil-infinity180** [celestiaorg/docs#972]
link https://docusaurus.io/docs

**Comment by jcstein** [comment]
thanks @manzil-infinity180 - would you like to make a PR to do this?

**Comment by jcstein** [comment]
actually, based on https://github.com/celestiaorg/docs/pull/971/files it looks like it already is in there!

**Comment by jcstein** [comment]
ah, unless you'd like to add a link specifically to the docs :)

**Comment by manzil-infinity180** [comment]
> ah, unless you'd like to add a link specifically to the docs :)

hello i just raise a PR for these checkout https://github.com/celestiaorg/docs/pull/977
